- mapcss_converter.py
On some systems (namely the Ubuntu 12.04 based Travis CI) importing just Image
fails. The more verbose version works on all systems tested so far.
> improve importing of Image library

- mapcss_converter.py
- cairo may be cairoffi, especially on Python 3
- make rsvg support optional as we currently don't need it
> add some workarounds for python modules

- mapcss_converter.py
This can be helpful if the output should be piped into another process.
> allow "-" to be specified as output file to force writing to stdout

- mapcss_converter.py
- tests/eval/join.pass_re
- tests/eval/numeric.pass_re
In case the value of a text element is calculated by a function (e.g. join())
the JavaScript code that did the calculation was added to the value_tags map:
MapCSS.e_join(" ", MapCSS.e_tag(tags, "razed:ref"), MapCSS.e_tag(tags, "razed:name"))
Check if the expression comes from an eval statement, and simply ignore it in
that case. Instead add the tags to the map when the call to MapCSS.e_tag() is
generated.
> fix JavaScript functions being added to value_tags map

- mapcss_converter.py
Use a new line for every single match expression in an if, this makes the
generated code much more readable.
> break lines in generated if statements

- tests/basic/objects_combined.pass_re
- tests/basic/objects_joined.pass_re
The file had the wrong name. While at it remove optional whitespace in the regex that is not there.
> fix the regular expression for the basic_objects_combined test

- mapcss_converter.py
- tests/basic/zoom/max.pass_re
- tests/basic/zoom/min.pass_re
- tests/basic/zoom/range.pass_re
- tests/basic/zoom/single.pass_re
This should make rendering at lower zoom levels much more efficient, as there
are many objects per tile and most expressions will probably not match because
of the zoom level. The check for the zoom level is relatively cheap as it is
just comparing two integers, so it avoids more expensive checks like string
equality or regular expression matches when those objects will not be drawn
anyway. On the other hand this makes rendering on lower zoom levels slightly
less efficient.
> move checks for the zoom level to the front of the expressions

- mapcss_converter.py
- tests/CMakeLists.txt
- tests/import.css
- tests/import/basic.pass_re
- tests/import/basic.tst
- tests/import/pseudoclass.pass_re
- tests/import/pseudoclass.tst
Otherwise it would fail with errors like this:
File "node-tileserver/tests/../mapcss_converter.py", line 144, in mapcss_as_aj
imports = "".join(map(lambda imp: propagate_import(imp.url).as_js, self.imports))
> fix "@import" statements

- kothic/style/mapcss.js
- mapcss_converter.py
- tests/basic/tag-values.pass_re
- tests/basic/tag-values.tst
- tests/eval/concat.pass_re
- tests/eval/concat.tst
- tests/eval/join.pass_re
Instead of e.g. concatenating the tag names for eval(join()), and then splitting stuff up again, looking up the tags and then adding their values do it the other way round: let e_tag() directly return the value, as otherwise e.g. cond() will not work. Use e_localize() inside the join() so the already localized values will be concatenated. Otherwise one may accidentially replace text with other text if a key with the given text exists.
> rework how e_localize() and e_tag() work

- kothic/renderer/texticons.js
This can now be achieved by using @media rules, so drop this custom property.
> drop kothicjs-ignore-text-offset-x support

- mapcss_converter.py
- tests/basic/selector/equal.pass_re
- tests/basic/selector/equal_quoted.pass_re
- tests/basic/selector/unequal.pass_re
- tests/basic/selector/unequal.tst
- tests/basic/selector/unequal_numeric.pass_re
- tests/basic/selector/unequal_numeric.tst
- tests/basic/selector/unequal_quoted.pass_re
- tests/basic/selector/unequal_quoted.tst
When checking a value against a number in case of equality currently the operator '==' was used (equality without type checking), but in case of inequality the operator '!==' was used (inequality with type checking). Since the value checked was always a string and the other value was a number the type was never the same and the inequality operator always returned true.
From now on the type equality is never used when comparing to a number, thus making it basically work as expected. When comparing other types (i.e. strings on both sides) always check for type equality to avoid any conversions from happening.
> use different operators when comparing with numbers

- kothic/renderer/path.js
This should fix all known instances of the "ghost lines" (#11). While at it it slightly reorders the rendering code, which should avoid some useless instruction during rendering.
> Fix rendering errors

- mapcss_converter.py
- mapcss_parser/ast.py
- tests/basic/class.pass_re
- tests/basic/class.tst
The parser already supports this, it's only the generated code that did not support this. Simply keep an array of the classes that were assigned to the current object and do a lookup if the object is within that class.
This fixes #66.
> Add support or classes

- kothic/style/mapcss.js
The MapCSS list proposal contains a join() function defined on a list, but there already is such a function for string arguments. Check the arguments passed into the function to select the correct implementation.
> merge the 2 colliding join() functions

- mapcss_parser/lex.py
- mapcss_parser/parse.py
- tests/basic/selector/regex.pass_re
- tests/basic/selector/regex.tst
- tests/known_bugs/parse/issue24-square-regex.ill
Until now the square brackets were taken as the opening brackets of selectors. Create a state for regular expressions to get a new matching scope. This also needs fixing of the p_condition_regex() function, which called an undefined class ConditionRegex. This was not hit until now because the rule never matched, until now regular expressions were matched as identifiers. From now on slashes are not allowed in identifiers anymore.
This fixes #24.
> allow square brackets in regular expressions

- kothic/renderer/shields.js
- kothic/renderer/texticons.js
- kothic/style/style.js
This adds support for the font-weight, font-style, and font-variant properties. It further removes some heuristics of the old code that were used to make bold and italic fonts at least sometimes work with the old code.
What does not work anymore is that only setting a font family to something that has "bold" in the name but not specifying "font-weight: bold", which has been fixed in [#420 in OpenRailwayMap](https://github.com/rurseekatze/OpenRailwayMap/pull/420).
This fixes #16 and #75.
> Rework font property handling

- tests/CMakeLists.txt
I think I have seen some errors that did not terminate the program, but can't remember where. Add a test for those.
> check for abort on all parse errors

- mapcss_parser/lex.py
Traceback (most recent call last):
File "node-tileserver/tests/../mapcss_converter.py", line 48, in <module>
from mapcss_parser import MapCSSParser
File "node-tileserver/mapcss_parser/__init__.py", line 27, in <module>
from mapcss_parser import lex
File "node-tileserver/mapcss_parser/lex.py", line 41
last_cr = 0
^
IndentationError: expected an indented block
> fix broken indentation

- mapcss_converter.py
The function was named "mapcss_as_aj", which looks like a typo. Rename it to "mapcss_as_js" to match the other handler functions.
> rename MapCSS object handler function

- mapcss_converter.py
If any of these conditions match no other will. Use elif constructs to only use the minimum number of checks.
> avoid duplicate checks on variable

- kothic/renderer/texticons.js
We currently don't need it, but it's so simple that there is no reason not to support it.
> add support for text-transform CSS property

- mapcss_parser/lex.py
- tests/CMakeLists.txt
- tests/errors/CMakeLists.txt
- tests/errors/illegal-char.err
- tests/errors/illegal-char.pass_re
Otherwise an incompletely transformed stylesheet may be output, hiding possible errors and making debugging harder.
> stop processing if an illegal character is found

- kothic/renderer/texticons.js
This is not only faster, it also makes sure no other labels can collide with these invisible labels, so more labels will be shown at the end.
> do not render labels that contain only whitespace

- mapcss_parser/lex.py
Testcase: an illegal character at the first position of a line.
If this is the first line:
Illegal character '(' at line 1 position 0
Otherwise:
Illegal character '(' at line 2 position 1
Make this consistent so the position is always reported 1-based.
> fix illegal character reporting in first line

- mapcss_converter.py
- mapcss_parser/ast.py
- mapcss_parser/lex.py
- mapcss_parser/parse.py
- tests/known_bugs/supports/extra-paren.ill
- tests/supports/and.fail_re
- tests/supports/and.pass_re
- tests/supports/and.tst
- tests/supports/decl.tst
- tests/supports/decl_rule_after.fail_re
- tests/supports/decl_rule_after.pass_re
- tests/supports/decl_rule_after.tst
- tests/supports/extra-paren-left.pass_re
- tests/supports/extra-paren-left.tst
- tests/supports/extra-paren-right.pass_re
- tests/supports/extra-paren-right.tst
- tests/supports/not.pass_re
- tests/supports/not.tst
- tests/supports/or.pass_re
- tests/supports/or.tst
- tests/supports/user-agent-match.pass_re
- tests/supports/user-agent-match.tst
- tests/supports/user-agent-no_match.tst
JOSM wants to phase out support for "@media", and use "@supports" instead. This parser is a bit more elaborate than the "@media" parser, and can also identify itself as "user-agent: node-tileserver".
This should allow merging [PR #451 in OpenRailwayMap](https://github.com/rurseekatze/OpenRailwayMap/pull/451).
> Add support for "@supports" statements

- kothic/kothic.js
Instead of creating an empty object and inserting it into the layersToRender array simply check if there was an object at all and stop doing any checks that must fail anyway.
The same change is now upstream in revision [285bd3d034af20b6c1b773e0a3a59ed436be273c](https://github.com/kothic/kothic-js/commit/285bd3d034af20b6c1b773e0a3a59ed436be273c).
> simplify filtering out empty layers

- kothic/renderer/path.js
Think of a square that is exactly the same size as the tile, but rotated by 45 degrees. Now the object in this tile consists of 8 points, 2 of them on each tile boundary. No line should be drawn between each of those pairs, because those are in fact no outer borders of the square. But the other lines were not drawn either because it was only checked if the points were on tile boundaries, but not on which ones.
From now on lines between points on tile borders will be drawn if the points are on distinct borders.
This fixes the rendering at http://www.openrailwaymap.org/?lang=en&lat=47.31991&lon=16.5636&zoom=18: one can see that there is actually something drawn in that tile http://b.tiles.openrailwaymap.org/standard/18/143133/91861.png.
> fix rendering of polygons where one border goes from one tile boundary to another

- tilerequest.js
- vectortilerequest.js
The detection uses the filename of the request to determine which data to return.
> allow vector tile request to return only the GeoJSON data

- mapcss_converter.py
This effectively fixes the indentation for code produced for "set .<classname>" instructions.
> use the same layout code for style and non-style statements

- mapcss_converter.py
Those were only inserted if additional criteria were present and not only the object type was matched. But since all criteria are a big and-expression anyway there is not need for parenthesis around that as the object type is combined with them with and, too.
> remove one pair of extra braces around conditions

- kothic/renderer/path.js
This does some restructuring and cleanups to make the code more similar to what is current upstream, where the custom dash code was entirely dropped in favor of native dashing done through the browser.
Since the upstream code has [some problems with casings](https://github.com/kothic/kothic-js/issues/60) it is not yet ready to be merged here.
> rework dash code

- kothic/renderer/path.js
Dashes are drawn from the last point a line ended to the current point. If the line is partly on a tile border it is not drawn there, but the last dash point is not updated, so the next dashed line will not start at the point where the line leaves the border, but at the point where it entered the border. Casing is implemented in terms of dashing, so it is also affected by this.
This is usually only visible for swmall narrow gauge tracks, e.g. in theme parks, as they are often tagged as a single, closed way. When this crosses a tile border the problem becomes visible.
> fix dash artifacts if line is partly on tile border

- bitmaptilerequest.js
- emptytile.json
- tile.js
While at it clean up the rendering code a little bit.
Fixes parts of #47.
> use hardlinks for empty bitmap tiles

- tile.js
Would lead to crashes otherwise as the already deleted tile object is used to process the same tile again.
> stop processing once an empty tile has been served

- package.json
- tile.js
This is to overcome the hard link limits of the filesystems.
> use multiple copies of the emptytile file as link targets

- kothic/renderer/texticons.js
This wraps the labels of polygons and points at different points, trying harder to paint them on the map. This greatly increases e.g. the number of stations names that can be shown on the map, as collisions with the tile borders are less likely to occur.
> Wrap labels

- kothic/renderer/texticons.js
They are more efficient and work with any version of JavaScript.
> replace for(... of) loops with normal for loops

- tilerequest.js
The exactly same message was logged just before the "if".
> remove duplicate log message in case of invalid parameters
